### ISSUE TITLE
Fix errors in AI

### ISSUE THREAD

**Issue by SpacialCircumstances** [solaris-games/solaris#1031]
```
ValidationError: The player does not own this carrier.
    at ShipTransferService.<anonymous> (/home/voxel/solaris/server/services/shipTransfer.ts:185:19)
    at Generator.next (<anonymous>)
    at /home/voxel/solaris/server/dist/services/shipTransfer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/voxel/solaris/server/dist/services/shipTransfer.js:4:12)
    at ShipTransferService.transfer (/home/voxel/solaris/server/dist/services/shipTransfer.js:161:16)
    at AIService.<anonymous> (/home/voxel/solaris/server/services/ai.ts:1323:44)
    at Generator.next (<anonymous>)
    at /home/voxel/solaris/server/dist/services/ai.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/voxel/solaris/server/dist/services/ai.js:4:12)
    at AIService._performLogistics (/home/voxel/solaris/server/dist/services/ai.js:916:16)
    at AIService.<anonymous> (/home/voxel/solaris/server/services/ai.ts:245:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/voxel/solaris/server/dist/services/ai.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400
}
```

```
ValidationError: The player does not own this carrier.
    at ShipTransferService.<anonymous> (/home/voxel/solaris/server/services/shipTransfer.ts:185:19)
    at Generator.next (<anonymous>)
    at /home/voxel/solaris/server/dist/services/shipTransfer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/voxel/solaris/server/dist/services/shipTransfer.js:4:12)
    at ShipTransferService.transfer (/home/voxel/solaris/server/dist/services/shipTransfer.js:161:16)
    at AIService.<anonymous> (/home/voxel/solaris/server/services/ai.ts:1323:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/voxel/solaris/server/dist/services/ai.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400
}
```

```
ValidationError: The waypoint Scatha -> Nira exceeds hyperspace range.
    at WaypointService.<anonymous> (/home/voxel/solaris/server/services/waypoint.ts:139:23)
    at Generator.next (<anonymous>)
    at /home/voxel/solaris/server/dist/services/waypoint.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/voxel/solaris/server/dist/services/waypoint.js:4:12)
    at WaypointService.saveWaypointsForCarrier (/home/voxel/solaris/server/dist/services/waypoint.js:39:16)
    at AIService.<anonymous> (/home/voxel/solaris/server/services/ai.ts:717:58)
    at Generator.next (<anonymous>)
    at fulfilled (/home/voxel/solaris/server/dist/services/ai.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400
```

**Comment by SpacialCircumstances** [comment]
#928
